services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    volumes:
      - ./dist:/var/lib/grafana/plugins/galileostdio-yellowbricks-datasource
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=galileostdio-yellowbricks-datasource